project_web_form/project_web_form/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
 
namespace project_web_form.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            
            ViewBag.Message = "<span> This Is My 'CRUD' Application </span> <br /> <span> you can 'Creat','Read','Update' or 'Delete' ;) </span>";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Contact";

            return View();
        }
    }
}

project_web_form/project_web_form/Controllers/studentController.cs
using project_web_form.context;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace project_web_form.Controllers
{
    public class studentController : Controller
    {
        // GET: student
        db_testEntities dbObj = new db_testEntities();

        public ActionResult Student(tbl_student obj)
        {
            
                return View(obj);
        }
        [HttpPost]
        public ActionResult AddStudent(tbl_student model)
        {
            if (ModelState.IsValid)
            {
                tbl_student obj = new tbl_student();
                obj.ID = model.ID;
                obj.Name = model.Name;
                obj.Fname = model.Fname;
                obj.Email = model.Email;
                obj.Mobile = model.Mobile;
                obj.Descritipion = model.Descritipion;
                if(model.ID == 0)
                {
                    dbObj.tbl_student.Add(obj);
                    dbObj.SaveChanges();
                }
                else
                {
                    dbObj.Entry(obj).State = EntityState.Modified;
                    dbObj.SaveChanges();
                }
                
                
            }
            ModelState.Clear();

            return View("Student");
        }



        public ActionResult StudentList()
        {
            var res = dbObj.tbl_student.ToList();
            
            return View(res);
        }

        public ActionResult Delete(int id)
        {
            var res = dbObj.tbl_student.Where(x => x.ID == id).First();
            dbObj.tbl_student.Remove(res);
            
            dbObj.SaveChanges();

            var list = dbObj.tbl_student.ToList();

            return View("StudentList",list);
        }
    }
}

project_web_form/project_web_form/Views/Home/About.cshtml
@{
    ViewBag.Title = "About My Application...";
}
<h2>@ViewBag.Title.</h2>
<h3>@Html.Raw(@ViewBag.Message)</h3>

<p></p>

project_web_form/project_web_form/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    <b>i'm Uzair Safdar</b><br />
    <b>Software Engineer</b><br />
    <b>Batch 2017</b> <br />
    <abbr title="Phone"><b>P:</b></abbr>
    <b>+923321621021</b>
</address>

<address>
    <strong>Marketing:</strong> <a href="https://www.facebook.com/uzair.safdar.90"target="_blank">https://www.facebook.com/uzair.safdar.90</a>
</address>
<address>
    <strong>Github:</strong> <a href="https://github.com/Ozair-eng"target="_blank">https://github.com/Ozair-eng</a>
</address>

project_web_form/project_web_form/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

project_web_form/project_web_form/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Student", "Student", "student", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    <li>@Html.ActionLink("StudentList", "StudentList", "student")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

project_web_form/project_web_form/Views/student/Student.cshtml
@model project_web_form.context.tbl_student
@{
    ViewBag.Title = "Student";
}

<style>
    .Error{
        color:red;

    }
</style>


@using (Html.BeginForm("Addstudent","Student",FormMethod.Post )) 
{
<div class="container">
       

    <div class="form-group">
        @Html.HiddenFor(x => x.ID)
        <label>Name</label><br />
        @Html.ValidationMessageFor(x => x.Name,"", new { @class = "Error" })

        @Html.TextBoxFor(x => x.Name, new { @class = "form-container" })
    </div>


    <div class="form-group">
        <label>Father Name</label><br />
        @Html.ValidationMessageFor(x => x.Fname,"", new { @class = "Error" })

        @Html.TextBoxFor(x => x.Fname, new { @class = "form-container" })
    </div>

    <div class="form-group">
        <label>Email</label><br />
        @Html.ValidationMessageFor(x => x.Email,"", new { @class = "Error" })

        @Html.TextBoxFor(x => x.Email, new { @class = "form-container" })
    </div>

    <div class="form-group">
        <label>Mobile</label><br />
        @Html.ValidationMessageFor(x => x.Mobile,"", new { @class = "Error" })

        @Html.TextBoxFor(x => x.Mobile, new { @class = "form-container" })
    </div>

    <div class="form-group">
        <label>Descritipion</label><br />
        @Html.ValidationMessageFor(x => x.Descritipion,"", new { @class = "Error" })

        @Html.TextAreaFor(x => x.Descritipion, new { @class = "form-container", @rows = "10" })
    </div>

    <div class="form-group"><br />
        <button type="submit" class="btn btn-primary">SUBMIT</button>
        <button type="reset" class="btn btn-danger">cancel</button>
    </div>
</div>     
}

project_web_form/project_web_form/Views/student/StudentList.cshtml
@model List<project_web_form.context.tbl_student>
@{
    ViewBag.Title = "StudentList";
}

<table class="table table-hover">
    <tr>
        <th>Name</th>
        <th>FName</th>
        <th>Email</th>
        <th>Mobile</th>
        <th>Description</th>
        <th>Action</th>
    </tr>

    @foreach (var item in Model) 
         {
        <tr>
            <td>@item.Name</td>
            <td>@item.Fname</td>
            <td>@item.Email</td>
            <td>@item.Mobile</td>
            <td>@item.Descritipion</td>
            <td>
                <a href="@Url.Action("Student", new {item.ID,item.Name,item.Fname,item.Mobile,item.Email,item.Descritipion} )" class="btn btn-success">Edit</a>

                <a href= "@Url.Action("Delete", new {item.ID})"  class="btn btn-danger">Delete</a>
            </td>

        </tr>
         }

</table>